title: Mahdi Javadi
logo: /assets/img/headshot_circle.png
theme: jekyll-theme-minimal

# Social links
social_links:
  - title: Twitter
    url: https://twitter.com/mahDI_javaDI
    icon: twitter
  - title: LinkedIn
    url: https://www.linkedin.com/in/m-javadi/
    icon: linkedin
  - title: GitHub
    url: https://github.com/m-djawadi
    icon: github
